server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://admin:admin_password@localhost/test?authSource=admin
      host: localhost 
      port: 27017
      database: test 
      username: admin 
      password: admin_password 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 8
    healthcheck:
      enabled : true
    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  app:
    name: catalog-service
    description: catalog-service
    version: 1.0.0

