server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 8
    healthcheck:
      enabled : true
    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info

info:
  app:
    name: movie-service
    description: movie-service
    version: 1.0.0