server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: mongodb://admin:admin_password@localhost/test?authSource=admin
      host: localhost 
      port: 27018
      database: test 
      username: admin 
      password: admin_password 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled : true
    service-url:
      default-zone: http://localhost:8761/eureka  
    instance:
      prefer-ip-address: false
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

    





    